sonar.projectKey=sample-java-app
sonar.projectName=Sample Java App
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.login=sqa_bcd0825f65501f8bfa1b2fbf3aa782393e1dcc57
